name: Android Build and Test CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - 'README.md'
    - '.github/workflows/**'
    
  pull_request:
    branches: [ "main", "development" ]
  
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean assembleDebug 
    - name: Run Instrumentation Tests
      run: ./gradlew DatabaseTest --continue
    - name: Upload Test Reports
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
          name: test-reports
          path: '**/build/reports/tests/'
